import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Herosection from "./components/Herosection";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import SideBarProvider from "@/contexts/SideBar/SideBarProvider";
import {AuthProvider} from "@/contexts/auth/AuthProvider";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head> <link href="https://api.fontshare.com/v2/css?f[]=clash-display@400&display=swap" rel="stylesheet"></link></head>
      <body className={inter.className} suppressHydrationWarning={true}>
      <AppRouterCacheProvider>  
        <AuthProvider>
          <SideBarProvider>
          {/* <Navbar /> */}

          <main>{children}</main>
          {/* <Footer/> */}
          </SideBarProvider>
        </AuthProvider>
        </AppRouterCacheProvider>
      </body>

    </html>
  );
}
